[package]
name = "contest"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
ethabi = "5.1.1"
ethereum-types = "0.3.2"
core-executor = { git = "https://github.com/cryptape/cita.git", branch = "develop" }
